//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuplicateNPL_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pair_request
    {
        public int id { get; set; }
        public System.Guid Uniqueid { get; set; }
        public string ContextKey { get; set; }
        public int Certificate_Id { get; set; }
        public Nullable<int> Sponsor_id { get; set; }
        public string MaxvalAPIRequestId { get; set; }
        public System.DateTime RequestDatetime { get; set; }
        public string Status { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public Nullable<int> pair_sync_id { get; set; }
        public Nullable<int> PairStatusId { get; set; }
        public string PairStatus { get; set; }
        public string PairStatusCode { get; set; }
        public string PairStatusDescription { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> EstimatedTimeToComplete { get; set; }
        public Nullable<System.DateTime> CompletedTime { get; set; }
        public Nullable<int> RequestTypeId { get; set; }
    }
}
