//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuplicateNPL_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_record_others
    {
        public int record_other_id { get; set; }
        public int record_id { get; set; }
        public string author { get; set; }
        public string vol_issue { get; set; }
        public string NPL_pub_date { get; set; }
        public string journal { get; set; }
        public string publisher { get; set; }
        public string page_no { get; set; }
        public string title { get; set; }
        public string url { get; set; }
        public string keywords { get; set; }
        public string @abstract { get; set; }
        public string citation { get; set; }
        public Nullable<byte> isactive { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<int> modified_user_id { get; set; }
        public Nullable<int> created_user_id { get; set; }
        public Nullable<byte> trans_mode_id_fk { get; set; }
        public string translation_comment { get; set; }
        public Nullable<int> Subcat_id_fk { get; set; }
        public string plaincitation { get; set; }
        public Nullable<byte> isreview { get; set; }
        public Nullable<int> IsDuplicateCheck { get; set; }
    
        public virtual tbl_record tbl_record { get; set; }
    }
}
