//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuplicateNPL_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pair_request_tracking
    {
        public int TrackingId { get; set; }
        public int PairRequestId { get; set; }
        public string RequestContextKey { get; set; }
        public string RequestParam { get; set; }
        public Nullable<bool> IsBiblioReceived { get; set; }
        public Nullable<bool> IsIFWReceived { get; set; }
        public Nullable<bool> IsOCRed { get; set; }
        public Nullable<bool> IsBiblioFailed { get; set; }
        public Nullable<bool> IsIFWFailed { get; set; }
        public Nullable<bool> IsOCRFailed { get; set; }
        public Nullable<int> ParentPairRequestId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
