//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuplicateNPL_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pair_references
    {
        public int id { get; set; }
        public Nullable<int> private_pair_id { get; set; }
        public string application_number { get; set; }
        public string references_number { get; set; }
        public Nullable<System.DateTime> references_date { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<int> record_id { get; set; }
        public Nullable<int> ref_state_id { get; set; }
        public Nullable<int> cited_source_id { get; set; }
        public string source_docket { get; set; }
        public string source_comments { get; set; }
        public Nullable<System.DateTime> cited_date { get; set; }
        public Nullable<int> record_type_id { get; set; }
        public Nullable<bool> is_processed { get; set; }
        public Nullable<bool> is_crossedOut { get; set; }
        public Nullable<int> ImportStatus { get; set; }
        public string Category { get; set; }
        public string pageno { get; set; }
        public string publicationdate { get; set; }
        public string inventor { get; set; }
        public string patentee { get; set; }
        public string cite_no { get; set; }
        public string row_status { get; set; }
        public string NPL_details { get; set; }
        public Nullable<int> toc_status { get; set; }
        public string applicant_name { get; set; }
        public string cpc_classifiction { get; set; }
        public string classifiction { get; set; }
        public string country_code { get; set; }
        public Nullable<System.DateTime> filing_date { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
        public string kind_code { get; set; }
        public Nullable<int> is_imported { get; set; }
        public string Class { get; set; }
        public string SubClass { get; set; }
        public string ExaminerInitial { get; set; }
        public Nullable<decimal> mxExaminerConsidered { get; set; }
        public Nullable<int> mxDataStatus { get; set; }
        public Nullable<bool> is_new_reference { get; set; }
        public string mxDocumentHandle { get; set; }
        public Nullable<int> mxAccuracy { get; set; }
        public string mxStatus { get; set; }
        public Nullable<int> IsDocumentSync { get; set; }
        public Nullable<int> IsMatched { get; set; }
        public Nullable<bool> IsFlagComments { get; set; }
        public string FlagComments { get; set; }
    
        public virtual tbl_private_pair tbl_private_pair { get; set; }
    }
}
