//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuplicateNPL_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_npl_duplicate_MergedLogs
    {
        public int Id { get; set; }
        public string PreviousRecordId { get; set; }
        public string DestinationRecordId { get; set; }
        public string Status { get; set; }
        public string Page { get; set; }
        public Nullable<int> PreviousPairReferenceId { get; set; }
        public Nullable<int> DestinationPairReferenceId { get; set; }
        public Nullable<int> PreviousImportReferenceId { get; set; }
        public Nullable<int> DestinationImportReferenceId { get; set; }
        public Nullable<int> TrackingId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
