//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuplicateNPL_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pair_references_FlagComments
    {
        public int Id { get; set; }
        public Nullable<int> pairReferenceId { get; set; }
        public string FlagComments { get; set; }
    }
}
