//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuplicateNPL_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_private_pair
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_private_pair()
        {
            this.tbl_pair_references = new HashSet<tbl_pair_references>();
            this.tbl_pair_references_header = new HashSet<tbl_pair_references_header>();
        }
    
        public int private_pair_id { get; set; }
        public string ApplicationNumber { get; set; }
        public string DocumentCategory { get; set; }
        public string DocumentDescription { get; set; }
        public Nullable<System.DateTime> MailRoomDate { get; set; }
        public Nullable<int> PageQuantity { get; set; }
        public string FileWrapperDocumentCode { get; set; }
        public string DownloadLink { get; set; }
        public Nullable<byte> IsPdfDownloaded { get; set; }
        public string PairFileName { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public string QC_REF_NUM { get; set; }
        public string PATENT_MASTER_ID { get; set; }
        public Nullable<System.DateTime> Upload_Date { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
        public string PairStatus { get; set; }
        public string DocumentId { get; set; }
        public Nullable<int> OCRRequestStatusId { get; set; }
        public Nullable<bool> IsIFWcode { get; set; }
        public string ReviewedUser { get; set; }
        public Nullable<bool> IsReferencePicker { get; set; }
        public Nullable<int> ReferencePickerId { get; set; }
        public Nullable<int> OcrStatus { get; set; }
        public string IDS_1449_Reference_FileName { get; set; }
        public Nullable<System.DateTime> Source_Cited_Date { get; set; }
        public string ReviewedBy { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
        public string ReviewedUserDatatime { get; set; }
        public Nullable<bool> IsImportWithRefData { get; set; }
        public string ReviewComments { get; set; }
        public string ReviewMessage { get; set; }
        public Nullable<int> ActivityAddedTypeId { get; set; }
        public Nullable<System.DateTime> IDS_Cited_Date { get; set; }
        public Nullable<int> IsMatched { get; set; }
        public Nullable<int> IsTocSaved { get; set; }
        public Nullable<int> IsIwrReviewed { get; set; }
        public Nullable<bool> IsOASyncCompleted { get; set; }
        public Nullable<int> Is_DuplicatesMerged { get; set; }
        public Nullable<System.DateTime> Is_DuplicatesMergedDateTime { get; set; }
        public Nullable<int> IsDocFormat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_pair_references> tbl_pair_references { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_pair_references_header> tbl_pair_references_header { get; set; }
    }
}
