//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuplicateNPL_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_npl_duplicate_Score
    {
        public int Id { get; set; }
        public Nullable<int> Record_Id { get; set; }
        public Nullable<int> Matching_Record_Id { get; set; }
        public Nullable<int> Score { get; set; }
        public bool IsActive { get; set; }
        public bool Is_Duplicate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Comments { get; set; }
        public string Source { get; set; }
        public bool IsProcessed { get; set; }
        public string Citation { get; set; }
    }
}
