//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuplicateNPL_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pair_references_header
    {
        public int id { get; set; }
        public int private_pair_id { get; set; }
        public string applicant { get; set; }
        public string application_number { get; set; }
        public string art_unit { get; set; }
        public string examiner_name { get; set; }
        public Nullable<int> total_pages { get; set; }
        public string FilingDate { get; set; }
        public string FirstNamedInventor { get; set; }
        public string AttorneyDocketNumber { get; set; }
        public string ConfirmationNumber { get; set; }
        public Nullable<int> mxDataStatus { get; set; }
    
        public virtual tbl_private_pair tbl_private_pair { get; set; }
    }
}
